CREATE SCHEMA IF NOT EXISTS AQFS;
USE AQFS;

CREATE TABLE PRODUCT
( 
PRODUCTID 	VARCHAR (30) NOT NULL, 
QUANTITY 	INT  NOT NULL,
TYPEA	VARCHAR (10),
NAMEA   VARCHAR (20) NOT NULL,
CONSTRAINT PRO_PKEY   PRIMARY KEY(PRODUCTID)
);


CREATE TABLE STAFF
( 
NAMEB 	 	        VARCHAR (40), 
PHONENO 	        VARCHAR (10),
NOA	        VARCHAR (400), 
CONSTRAINT  STAFF_PK PRIMARY KEY(NOA)
 );
 
 
CREATE TABLE PARTTIME
( 
HRWORKED 	  VARCHAR (99)  NOT NULL, 
RATEPERHR      VARCHAR (30) NOT NULL,  
CONSTRAINT  PARTTIME_PK PRIMARY KEY(HRWORKED)
);

CREATE TABLE FULLTIME
( 
SALARY 	  VARCHAR (6)  NOT NULL, 
CONSTRAINT  FULLTIME_PK PRIMARY KEY(SALARY)
);

 
CREATE TABLE CUSTOMER
( 
CUSTOMERID 	  BIGINT  NOT NULL, 
CUSTOMERNAME      VARCHAR (30),  
CUSTOMERADDRESS    VARCHAR(100) NOT NULL,
CONSTRAINT  CUSTOMER_PK PRIMARY KEY(CUSTOMERID)
);


CREATE TABLE CUSTOMERPAYMENTS
(
INVOICENO   BIGINT NOT NULL,
CONSTRAINT CUSTOMERPAYMENTS_PK PRIMARY KEY(INVOICENO)
);

CREATE TABLE PAYMENTS
(
TIMEA TEXT,
PAYMENT BIGINT NOT NULL,
DATEA VARCHAR(365),
METHOD VARCHAR(5) NOT NULL,
CONSTRAINT PAYMENTS_PK PRIMARY KEY(PAYMENT)
);

CREATE TABLE ORDERA
(
ORDERNO BIGINT NOT NULL,
CONSTRAINT ORDERA_PK PRIMARY KEY(ORDERNO)
);


INSERT INTO PRODUCT VALUES  ('29',   '14' ,'DAIRY','MILK');
INSERT INTO PRODUCT VALUES  ('19',   '602' ,'MISC', 'BAG');
INSERT INTO PRODUCT VALUES  ('22',   '32' ,'HYGIENE', 'SOAP');
INSERT INTO PRODUCT VALUES  ('9',   '300' ,'TEA', 'TEA');

INSERT  INTO   STAFF VALUES  ('DAIRE ONEILL', '0894222071', 302);
INSERT  INTO   STAFF VALUES  ('VAL LAMBE', '0862220091', 199);
INSERT  INTO   STAFF VALUES  ('DYLAN WISE', '0871111143', 332);


INSERT  INTO   PARTTIME VALUES  ('39', '11');
INSERT  INTO   PARTTIME VALUES  ('25', '10.50');

INSERT  INTO   FULLTIME VALUES  ('50,000');



 
INSERT  INTO   CUSTOMER VALUES  ('12321', 'DON SHERIDAN',  '18 COOL STREET WATERFORD');
INSERT  INTO   CUSTOMER VALUES  ('161', 'ALICE CACHIL',  '21 FIRST ROAD KILKENNY');
INSERT  INTO   CUSTOMER VALUES  ('1222', 'HEATHER DENNY',  '11 SEVENTH ROAD WATERFORD');
INSERT  INTO   CUSTOMER VALUES  ('2261', 'BRIAN DYLAN',  '21 NINTH ROAD KILKENNY');

 
INSERT  INTO   CUSTOMERPAYMENTS VALUES  ('898890');
INSERT  INTO   CUSTOMERPAYMENTS VALUES  ('832440');


INSERT  INTO   PAYMENTS VALUES  ('13:13:23', '8983', '14/06/21' , 'CARD');
INSERT  INTO   PAYMENTS VALUES  ('08:23:11', '222', '12/12/21' , 'CASH');
INSERT  INTO   PAYMENTS VALUES  ('15:10:01', '323232', '30/05/21' , 'CARD');
INSERT  INTO   PAYMENTS VALUES  ('19:21:54', '123213', '23/02/21' , 'CARD');

INSERT INTO    ORDERA VALUES  ('123');
INSERT INTO    ORDERA VALUES  ('1553');


CREATE USER MANAGER IDENTIFIED BY 'BOSS';
CREATE USER ASSISTANT IDENTIFIED BY 'ASSI';

GRANT ALL ON AQFS TO MANAGER;

GRANT SELECT ON PRODUCT TO ASSISTANT;
GRANT UPDATE (QUANTITY) ON PRODUCT TO ASSISTANT;