USE AQFS;
-- USES THE TABLE AQFS


SELECT NAMEA, QUANTITY FROM PRODUCT;
-- GIVES US THE NAME AND QUANTITY STORED IN PRODUCTS


UPDATE PRODUCT
SET QUANTITY = 13
WHERE NAMEA='MILK';
-- SETS THE QUATITY TO A DIFFERNT AMOUNT


SELECT NAMEB, PHONENO, NOA FROM STAFF;
-- GIVES US THE NAME, PHONE NUMBER AND STAFFID NUMBER STORED IN STAFF


SELECT CUSTOMERID, CUSTOMERADDRESS FROM CUSTOMER;
-- GIVES US THE CUSTOMER ID AND ADDRESS STORED IN CUSTOMER


SELECT ORDERNO FROM ORDERA;
-- GIVES US THE ORDER NUMBER STORED IN ORDERA